package com.mipyme.company;


public enum PlanFeature {
    FACTURACION_ARCA,
    METRICAS_AVANZADAS,
    AUDITORIA_AVANZADA,
    BRANCH_MANAGEMENT,
    WAREHOUSE_MANAGEMENT,
    ADVANCED_PERMISSIONS,
    EXPORTACIONES,
    FREQUENT_CUSTOMERS,
}
